/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusesIdRouteImport } from './routes/bonuses.$id'
import { Route as BenefitsIdRouteImport } from './routes/benefits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesIdRoute = BonusesIdRouteImport.update({
  id: '/bonuses/$id',
  path: '/bonuses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIdRoute = BenefitsIdRouteImport.update({
  id: '/benefits/$id',
  path: '/benefits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/bonuses/$id': typeof BonusesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/bonuses/$id': typeof BonusesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/bonuses/$id': typeof BonusesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benefits/$id' | '/bonuses/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benefits/$id' | '/bonuses/$id'
  id: '__root__' | '/' | '/benefits/$id' | '/bonuses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenefitsIdRoute: typeof BenefitsIdRoute
  BonusesIdRoute: typeof BonusesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses/$id': {
      id: '/bonuses/$id'
      path: '/bonuses/$id'
      fullPath: '/bonuses/$id'
      preLoaderRoute: typeof BonusesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/$id': {
      id: '/benefits/$id'
      path: '/benefits/$id'
      fullPath: '/benefits/$id'
      preLoaderRoute: typeof BenefitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenefitsIdRoute: BenefitsIdRoute,
  BonusesIdRoute: BonusesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
